sudo: required
dist: trusty
language: python
python:
  - "2.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install curl
  - curl -L https://bootstrap.saltstack.com -o bootstrap_salt.sh
  - sudo bash bootstrap_salt.sh -d
  - sudo mkdir -p /srv
  - chmod 755 travis/build.sh
  - chmod 755 travis/test.sh

install:
  - pip install -r travis/requirements.txt

script:
 - sudo -H travis/build.sh
 - sudo travis/test.sh $(which py.test)
