# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "wicksycv" do |wicksycv|

    wicksycv.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end

    wicksycv.vm.box = "ubuntu/xenial64"
    wicksycv.vm.network "private_network", ip: "192.168.168.192"
    wicksycv.vm.hostname = "wicksycv"
    wicksycv.vm.synced_folder "../salt/roots/", "/srv/salt/"
    wicksycv.vm.synced_folder "../salt/pillar/", "/srv/pillar/"
    wicksycv.vm.synced_folder "../ansible/", "/srv/ansible/"

    wicksycv.vm.provision :salt do |salt|

      salt.masterless = true
      salt.minion_config = "../salt/minion"
      salt.run_highstate = true

    end

  end

end
